name: Run workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *' # Everyday at 4 pm
  push:
    branches:
    - main
  
  

jobs:
  push-data:
    runs-on: windows-latest
    permissions:
      contents: write  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
    - name: Install packages from renv lockfile
      uses: r-lib/actions/setup-renv@v2

    - name: Run automation
      run: Rscript -e 'source("R/auto workflow.R")'


    - name: Set up Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Stage and commit data changes
      run: |
        git add . --verbose
        git commit -m "Re-ran scrape at $(date +'%Y-%m-%d')" || echo "No changes to commit"
        git push origin main || echo "No changes to commit"