name: Re-run scrape

on:
  workflow_dispatch:

jobs:
  push-data:
    runs-on: windows-latest
    permissions:
      contents: write  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
    - name: Install packages from renv lockfile
      uses: r-lib/actions/setup-renv@v2

    - name: Run automation
      run: Rscript -e 'source("auto workflow.R")'


    - name: Set up Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
    - name: Stage and commit data changes
      run: |
        git add data/ --verbose
        git commit -m "Automated commit of data files" || echo "No changes to commit"
        git push origin main || echo "No changes to commit"