name: test
on:
  workflow_dispatch:
jobs:
    - name: Commit results
    run: |
              git config --local user.email "actions@github.com"
              git config --local user.name "GitHub Actions"
              git add data/*
              git commit -m 'test succed' || echo "No changes to commit"
              git push origin || echo "No changes to commit"