name: Check if pocast changed
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *' # At 12:00 UTC

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    steps:
    - uses: r-lib/actions/setup-r@v2
    - name: Install packages
    uses: r-lib/actions/setup-r-dependencies@v2
    with:
    paclages: |
      any::tidyverse
      any::rvest
      any::cli
      any::collapse
      any::stringi
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-renv@v2        
    - name: Run R script
      run: Rscript -e 'source("auto workflow.R")'
    - name: Commit and push if changes
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data/*
          git commit -m "Automatic action completed: updated files" || echo "No changes to commit"
          git push origin main || echo "No changes to commit"
