name: Check if pocast changed
on:
  schedule:
    - cron: '0 0 * * 0' # At 00:00 on Sunday

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up R
        uses: r-lib/actions/setup-r@v3
      - name: Install R packages
        run: Rscript -e 'install.packages(c("collapse", "rvest","stringi","tidyverse","snakecase","jsonlite","tidytext","stopwords","tidylo","quanteda","marquee","hms"))'
      - name: Run R script
        run: Rscript auto workflow.R
      - name: Commit and push if changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data/*
          git commit -m "Automatic action completed: updated files" || echo "No changes to commit"
          git push origin main || echo "No changes to commit"
